services:
  app:
    image: composer
    container_name: yii2_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: sh -c 'docker-php-ext-install pdo_mysql && composer install && php -S 0.0.0.0:8080 -t web'
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii2_db
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2_phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    expose:
      - 8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  db_data:
