name: test

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: yii2db
          MYSQL_USER: yii2user
          MYSQL_PASSWORD: yii2password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer --version

      - name: Install dependencies
        working-directory: ./app
        run: composer install

      - name: Update DB Host in Config
        run: |
          sed -i 's/host=db/host=127.0.0.1/' ./app/config/db.php

      - name: Run Migrations       
        working-directory: ./app
        run: |          
          php yii migrate --interactive=0

      - name: Test
        working-directory: ./app
        run: |
          php vendor/bin/codecept run
