name: test

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer --version

      - name: Install dependencies
        working-directory: ./app
        run: composer install

      - name: Setup MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start

      - name: Configure MySQL
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Create Database and User
        run: |
          mysql -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS yii2db;"
          mysql -u root -proot_password -e "CREATE USER IF NOT EXISTS 'yii2user'@'localhost' IDENTIFIED BY 'yii2password';"
          mysql -u root -proot_password -e "GRANT ALL PRIVILEGES ON yii2db.* TO 'yii2user'@'localhost';"
          mysql -u root -proot_password -e "FLUSH PRIVILEGES;"

      - name: Run Migrations
        working-directory: ./app
        run: |
          php yii migrate --interactive=0

      - name: Test
        working-directory: ./app
        run: |
          php vendor/bin/codecept run
