name: test

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Defina a versão do PHP conforme necessário

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '1a...') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install dependencies
        run: composer install

      - name: Setup MySQL
        run: sudo apt-get install -y mysql-server

      - name: Create Database
        run: |
          mysql -e "CREATE DATABASE IF NOT EXISTS my_database;"

      - name: Run Migrations
        run: |
          php yii migrate --interactive=0

      - name: Test
        run: |
          php vendor/bin/codecept run
